refs #6
CubanTech/slides.cuban.tech pull request #7
Opened 2019-06-26 02:20 UTC by armas00

Traduccion inicial

2019-07-08 04:09 UTC, olemis requested changes
ensure suggested changes applied across document

2019-07-08 04:09 UTC, olemis commented on skycoin.intro-es.md
> +Red: cubantech
red => SSID

2019-07-08 04:09 UTC, olemis commented on skycoin.intro-es.md
> +- Comprendiendo las transacciones Skycoin
de Skycoin

2019-07-08 04:09 UTC, olemis commented on skycoin.intro-es.md
> +- ¿Próximo paso?
Próximos

2019-07-08 04:09 UTC, olemis commented on skycoin.intro-es.md
> +- Contabilidad y economía
y finanzas

2019-07-08 04:09 UTC, olemis commented on skycoin.intro-es.md
> +  * ... incluso si es posible Turing completo
incluso si pueden ser Turing completas

2019-07-08 04:09 UTC, olemis commented on skycoin.intro-es.md
> +- Recibir solicitudes de los clientes (entiéndase entradas)
entiéndase => i.e.

2019-07-08 04:09 UTC, olemis commented on skycoin.intro-es.md
> +- Monitorear las réplicas buscando diferencias en el Estado o la Salida
Monitorear diferencias en el Estado o las Salidas de las réplicas

2019-07-08 04:09 UTC, olemis commented on skycoin.intro-es.md
> +- Herramientas de gestión de contenedores (Ansible, Puppet, Chef, Habitat, ...)
gestión de configuración

2019-07-08 04:09 UTC, olemis commented on skycoin.intro-es.md
> +## Estado de la gestión de contenedores - Primer trimestre 2017
gestión de configuración

2019-07-08 04:09 UTC, olemis commented on skycoin.intro-es.md
> +## Bitcoin - Anatomía de de las transacciones
de de => de

2019-07-08 04:09 UTC, olemis commented on skycoin.intro-es.md
> +- Fecha de fijación
por el momeno dejarlo como `locktime` , pues no creo q `momento de fijación` sea correcto .

2019-07-14 17:12 UTC, armas00 commented
Sorry for commenting and commiting previously in Spanish.
Suggested changes were applied across document. Also, I figured out you wanted same changes for skycoin.intro applied in skycoin.libs where possible. Done!

2019-07-19 20:17 UTC, merged